### ISSUE TITLE
Error when generating swagger spec

### ISSUE THREAD

**Issue by jlsubia404** [open-wa/wa-automate-docker#10]
I have the next error when I run docker-compose up --build.

`Error File not found: /usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.ts FileNotFoundError: File not found: /usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.ts
app_1      |     at DirectoryCoordinator.addSourceFileAtPath (/usr/src/app/node_modules/ts-morph/dist/ts-morph.js:17851:19)
app_1      |     at Project.addSourceFileAtPath (/usr/src/app/node_modules/ts-morph/dist/ts-morph.js:19289:51)
app_1      |     at /usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:107:42
app_1      |     at step (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:63:23)
app_1      |     at Object.next (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:44:53)
app_1      |     at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:35:58)`

**Comment by smashah** [comment]
@jlsubia404 when did you last try this?

**Comment by manojsitapara** [comment]
@smashah I am also getting same error, just now I did try

`- Authenticate to continue
- Reinjecting api
- WAPI Reinjected
- Checking if session is valid
- Client is ready
- Installing patches
- Patches Installed
- Client loaded in 26.503s
- 🚀 @OPEN-WA ready for account: 8097
Generating Swagger Spec
Error File not found: /usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.ts FileNotFoundError: File not found: /usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.ts
    at DirectoryCoordinator.addSourceFileAtPath (/usr/src/app/node_modules/ts-morph/dist/ts-morph.js:17851:19)
    at Project.addSourceFileAtPath (/usr/src/app/node_modules/ts-morph/dist/ts-morph.js:19289:51)
    at /usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:107:42
    at step (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:63:23)
    at Object.next (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:44:53)
    at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  path: '/usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.ts',
  code: 'ENOENT'
}`

**Comment by smashah** [comment]
@manojsitapara can you confirm that you are using V3.6.10

**Comment by manojsitapara** [comment]
@smashah it is 3.6.11

> '│ WA_AUTOMATE_VERSION │  '3.6.11'
