### ISSUE TITLE
Error on refresh API

### ISSUE THREAD

**Issue by MarStefo** [open-wa/wa-automate-docker#22]
Hi, when I run `http://localhost:8080/refresh` from the API, I get the following response:

```
{
  "success": false,
  "error": {
    "name": "Error",
    "message": "Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined\n    at __puppeteer_evaluation_script__:1:117221\n    at __puppeteer_evaluation_script__:1:450370"
  }
}
```

Also, I am unable to send messages, but I think it is due to the previous error.

**Comment by smashah** [comment]
> Hi, when I run `http://localhost:8080/refresh` from the API, I get the following response:
> 
> ```
> {
>   "success": false,
>   "error": {
>     "name": "Error",
>     "message": "Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined\n    at __puppeteer_evaluation_script__:1:117221\n    at __puppeteer_evaluation_script__:1:450370"
>   }
> }
> ```
> 
> Also, I am unable to send messages, but I think it is due to the previous error.
> 
> <img alt="Screenshot 2021-11-11 at 12 36 39" width="1066" src="https://user-images.githubusercontent.com/6590445/141291617-4a3ddde3-2860-4c2f-9c79-49ab00170ce2.png">

Can you share the screenshot of all the logs please not just the error. There's no context otherwise

**Comment by MarStefo** [comment]
Hi @ smashah, 

Ok, I am attaching the entire log, anyway to reproduce my error:
1. Docker-compose built and started;
2. Authentication performed with smartphone through QR code;
3. Tested the API on the Web UI (but I get the same result with Postman too), in particular:
   i. `/sendText` correctly responds to the request but does NOT actually send the message, although it indicates it as done
   ii. `/refresh` responds with the error displayed above.

## /sendText
Request:
```
{
  "args": {
    "to": "39320xxxxxxx[redacted]@c.us",
    "content": "Hello World!"
  }
}
```
Response:
```
{
  "success": true,
  "response": "true_39320xxxxxxx[redacted]@c.us_[redacted]_out"
}
```
But the message is not actually sent.

<details>
<summary>Open logs...</summary>
<p>

```
- Launching EASY API
2021-11-12T08:54:52.982866000Z - Selected port is free
2021-11-12T08:54:52.984087000Z - Generating Swagger Spec
2021-11-12T08:54:54.135262000Z - Postman collection generated: open-wa-session.postman_collection.json
2021-11-12T08:54:54.336078900Z - API collections (swagger + postman) generated successfully
2021-11-12T08:54:54.480370300Z ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.23.9                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━��━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
2021-11-12T08:54:54.601082100Z You can also authenticate the session at: http://localhost:8080
2021-11-12T08:54:54.601645700Z - Starting
2021-11-12T08:54:54.602303600Z - Version: 4.23.9
2021-11-12T08:54:54.602467300Z - Initializing WA
2021-11-12T08:54:54.603894100Z - Launching Browser
2021-11-12T08:54:55.770430500Z - Setting Up Browser
2021-11-12T08:54:55.776222400Z - Loading session data
2021-11-12T08:54:55.777090800Z - No session data file found for session : session
2021-11-12T08:54:55.777253800Z - Navigating to WA
2021-11-12T08:54:58.071718800Z - Page loaded in 2293ms: 200
2021-11-12T08:54:58.071875500Z - Browser Launched
2021-11-12T08:54:58.120497800Z - Debug info: {
2021-11-12T08:54:58.120580600Z   "WA_VERSION": "2.2144.8",
2021-11-12T08:54:58.120607500Z   "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
2021-11-12T08:54:58.120636800Z   "WA_AUTOMATE_VERSION": "4.23.9",
2021-11-12T08:54:58.120664100Z   "BROWSER_VERSION": "HeadlessChrome/79.0.3945.88",
2021-11-12T08:54:58.120688400Z   "OS": "Linux 5.10",
2021-11-12T08:54:58.120717100Z   "START_TS": 1636707298086
2021-11-12T08:54:58.120744200Z }
2021-11-12T08:54:58.121769500Z - Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2144.8%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.23.9%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/79.0.3945.88%22,%0A%20%20%22START_TS%22:%201636707298086%0A%7D&environment=-%20OS:%20Linux%205.10%0A-%20Node:%2017.1.0%0A-%20npm:%20%0A
2021-11-12T08:54:58.122357400Z - Injecting api
2021-11-12T08:54:59.670733600Z - WAPI injected
2021-11-12T08:54:59.670987900Z - Authenticating
2021-11-12T08:54:59.786319200Z - Authenticate to continue
2021-11-12T08:55:02.473705800Z 
[QR CODE]
2021-11-12T08:55:02.474351300Z 
2021-11-12T08:55:10.649212900Z - QR code scanned. Loading session...
2021-11-12T08:55:12.371256700Z - QR code scanned. Loading session...
2021-11-12T08:55:12.371536500Z - Reinjecting api
2021-11-12T08:55:13.921249600Z - WAPI Reinjected
2021-11-12T08:55:13.921312000Z - Checking if session is valid
2021-11-12T08:55:13.932575000Z - Downloading patches from https://cdn.openwa.dev/patches.json
2021-11-12T08:55:13.932840900Z - Client is ready
2021-11-12T08:55:14.537241500Z - Generating patch hash
2021-11-12T08:55:14.557466400Z - Downloaded patches in 0.603s
2021-11-12T08:55:14.558962900Z - Installing patches
2021-11-12T08:55:15.156658000Z - Patches Installed: f814e
2021-11-12T08:55:15.580079000Z - Client loaded for normal account with 711 contacts, 181 chats & 450 messages in 21.174s
2021-11-12T08:55:16.078062800Z - Finalizing web session...
2021-11-12T08:55:16.386012500Z - Finalizing client...
2021-11-12T08:55:18.298481100Z - 🚀 @OPEN-WA ready for account: 8165
2021-11-12T08:55:18.300605700Z - session_STARTUP
2021-11-12T08:55:18.300776200Z - Setting Up API Explorer
2021-11-12T08:55:18.313309900Z - API Explorer set up successfully
2021-11-12T08:55:18.313517700Z - ...waiting for port 8080 to be free
2021-11-12T08:55:18.318586200Z - Port 8080 is now free.
2021-11-12T08:55:18.318906900Z - 
2021-11-12T08:55:18.319025200Z 	API Explorer (​http://localhost:8080/api-docs/ ​)
2021-11-12T08:55:18.320060300Z - 
2021-11-12T08:55:18.320107400Z • Listening on port 8080!
2021-11-12T08:56:12.572458900Z - 
2021-11-12T08:56:12.572634800Z • Listening on port 8080!
2021-11-12T08:56:12.572658200Z - session_REFRESH
2021-11-12T08:56:12.572716600Z - 
2021-11-12T08:56:12.572758100Z • Listening on port 8080!
2021-11-12T08:56:12.572850500Z - Refreshing session
2021-11-12T08:56:12.572873900Z - 
2021-11-12T08:56:12.572896000Z • Listening on port 8080!
2021-11-12T08:56:12.572912700Z - Opening session in new tab
2021-11-12T08:56:12.887295000Z - 
2021-11-12T08:56:12.887351700Z • Listening on port 8080!
2021-11-12T08:56:12.887376000Z - Waiting for conflict to close stale tab...
2021-11-12T08:56:13.110442100Z - 
2021-11-12T08:56:13.110492700Z • Listening on port 8080!
2021-11-12T08:56:13.110513500Z - Checking if fresh session is authenticated...
2021-11-12T08:56:13.136932000Z - 
2021-11-12T08:56:13.136997100Z • Listening on port 8080!
2021-11-12T08:56:13.137021300Z - Injected new session...
2021-11-12T08:56:13.417943800Z - 
2021-11-12T08:56:13.418013700Z • Listening on port 8080!
2021-11-12T08:56:13.418037000Z - Downloading patches from https://cdn.openwa.dev/patches.json
2021-11-12T08:56:13.647323800Z - 
2021-11-12T08:56:13.647375700Z • Listening on port 8080!
2021-11-12T08:56:13.647647200Z - Generating patch hash
2021-11-12T08:56:13.653905100Z - 
2021-11-12T08:56:13.653970400Z • Listening on port 8080!
2021-11-12T08:56:13.654123300Z - Downloaded patches in 0.23s
2021-11-12T08:56:13.654642800Z - 
2021-11-12T08:56:13.654725600Z • Listening on port 8080!
2021-11-12T08:56:13.654748900Z - Installing patches
2021-11-12T08:56:14.053148800Z middleware -> error Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined
2021-11-12T08:56:14.053342800Z     at __puppeteer_evaluation_script__:1:117221
2021-11-12T08:56:14.053368700Z     at __puppeteer_evaluation_script__:1:450370
2021-11-12T08:56:14.053390400Z     at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:175:23)
2021-11-12T08:56:14.053413400Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-11-12T08:56:14.053437900Z     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
2021-11-12T08:56:14.053460500Z     at async Promise.all (index 0)
```

</p>
</details>

**Comment by smashah** [comment]
@MarStefo can you try this again please

**Comment by smashah** [comment]
<img width="986" alt="CleanShot 2021-11-21 at 04 19 22@2x" src="https://user-images.githubusercontent.com/5903821/142749465-dc80e695-7095-489f-9588-3ce2fb51860f.png">

Wow this is what the new page looks like. This is why this is happening
