### ISSUE TITLE
Error in openwa/wa-automate:latest docker mage 

### ISSUE THREAD

**Issue by willmaraujo** [open-wa/wa-automate-docker#47]
I'm getting this error when run 

`docker run -p 8081:8080 --init openwa/wa-automate --multi-device`

During the container initialisation comes the error:

```
You can also authenticate the session at: http://localhost:8080
- Starting
- Version: 4.40.2
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them:
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Data dir doesnt exist, creating...: /sessions/_IGNORE_session
- Browser launched: 908ms
TypeError: waPage._client.send is not a function
    at /usr/src/app/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:71:24
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:24:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
- session_STARTUP
- Error waPage._client.send is not a function TypeError: waPage._client.send is not a function
```

**Comment by smashah** [comment]
that's an extremely odd and unexpected error and am unable to replicate here.

Please try this:

```bash
> docker pull openwa/wa-automate:latest
> docker run -p 8081:8080 --init openwa/wa-automate:latest
```

**Comment by smashah** [comment]
Resolved in latest version. This is due to pptr changes and mismatches

**Comment by willmaraujo** [comment]
Perfect, thank you so much for the quick reply. No it's working perfectly!
