### ISSUE TITLE
Evaluation failed: TypeError: WAPI.healthCheck is not a function

### ISSUE THREAD

**Issue by wira-works** [open-wa/wa-automate-docker#48]
after some periode, need to scan qr code again. this the error logs :

- Injecting scripts
- Base inject: 397ms
- Launch inject: 1890ms
- Injecting scripts
- Base inject: 1438ms
- Launch inject: 1300ms
- Injecting scripts
- Base inject: 68ms
- Injecting scripts
- Launch inject: 3796ms
- Base inject: 2910ms
- Injecting scripts
- Base inject: 1818ms
- Injecting scripts
- Base inject: 492ms
- WAPI inject: 3208ms
- Checking session integrity
- Session integrity check failed, trying again... 3
- WAPI inject: 3511ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 4096ms
- Launch inject: 8628ms
middleware -> error Error: Evaluation failed: TypeError: WAPI.healthCheck is not a function
    at pptr://__puppeteer_evaluation_script__:1:13
    at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)

**Comment by ahmeaqas** [comment]
Whatsapp page is crashed, hence Puppeteer is poping up the error.

Restart the docker container and scan the qr once again.
