### ISSUE TITLE
Not working on raspberrypi 

### ISSUE THREAD

**Issue by barart** [open-wa/wa-automate-docker#53]
Hello, im trying to run the container on a raspberrypi with raspberrypi os Debian version: 11 (bullseye) 64bit using the WA_RASPI=true enviroment and what i got is this:

```
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT
    at onClose (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:283:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
- session_STARTUP
- Error Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT
 Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT
```

I think that is looking for binary chromium-browser but that binary does not exists, on raspberry pi os i see that there is a package called chromium but not chromium-browser idk if changing to install chromium instead chromium-browser and launch the browser with chromium will fix this

**Comment by fejorca** [comment]
I'm having this same issue but with oracle instance with ampere cpu, even changing W_A_V env variable version doesn't help
