### ISSUE TITLE
Error during container initialisation

### ISSUE THREAD

**Issue by willmaraujo** [open-wa/wa-automate-docker#65]
I'm using the latest version for openwa/wa-automate container

```
| You can also authenticate the session at: http://localhost:8002
- Starting
- Version: 4.64.2
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them:
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Data dir doesnt exist, creating...: /sessions/_IGNORE_session
Error: Failed to launch the browser process! spawn /usr/bin/google-chrome ENOENT
```

**Comment by smashah** [comment]
@willmaraujo are you running this on m1/arm?

**Comment by willmaraujo** [comment]
> @willmaraujo are you running this on m1/arm?
> 
> 

I'm running in a raspberry pi (ARM). It was working perfectly since last year.

**Comment by willmaraujo** [comment]
@smashah here's the entire log

```
You can also authenticate the session at: http://localhost:8002
- Starting
- Version: 4.64.3
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them:
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Data dir doesnt exist, creating...: /sessions/_IGNORE_session
- Error launching browser
Error: Failed to launch the browser process! spawn /usr/bin/google-chrome ENOENT


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/owauser/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:289:27)
    at ChromeLauncher.executablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:163:25)
    at PuppeteerNode.executablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:156:105)
    at /usr/src/app/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:511:72
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
- session_STARTUP
- Error Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/owauser/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/owauser/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
```

**Comment by smashah** [comment]
please try the latest image
